Fix count samples from annotations
sigmf/sigmf-python pull request #47
Opened 2024-01-18 12:54 UTC by vejretvejret

Fixed two scenarios where SigMFFile._count_samples() failed:

1. No data_file registered: sample_count should be calculated from annotation with highest end index, not from annotation with highest start index
2. If no core:sample_count is provided in the annotation, core:sample_start should be used (sample count must at least be equal to this)

2024-01-18 21:43 UTC, Teque5 requested changes
Thanks for fixing the bug, just a few alterations and this is good.

2024-01-18 21:43 UTC, Teque5 commented on tests/testdata.py
> +TEST_METADATA_MULTI_ANNON = {
Instead of duplicating `TEST_METADATA`, can you copy and just override `ANNOTATION_KEY`?

2024-01-18 21:43 UTC, Teque5 commented on sigmf/sigmffile.py
>          ]
I think 5 lines of logic within a list comprehension is too many. Please break this out so it is more clear like
```python
annots = []
for annot in self._metadata.get(self.ANNOTATION_KEY, []):
   annotation_logic()
return annots
```

2024-01-18 21:43 UTC, Teque5 commented on tests/test_sigmffile.py
> +            ])
```suggestion
            ]
        )
```

2024-01-18 21:43 UTC, Teque5 commented on tests/test_sigmffile.py
> +    def test__count_samples_from_annotation(self):
please add docstrings to these test functions

2024-01-19 08:17 UTC, vejretvejret commented
Requested changes addressed

2024-01-19 17:40 UTC, merged